Final Capstone Project: Home page and About page
ndorrh/final-capstone pull request #2
Opened 2022-09-14 13:49 UTC by ndorrh

This project is a part of microverse training program. It was built using HTML5, CSS, JavaScript, and BS5.
It is a web application for a web development boot camp. In this project I implemented the following:

1) **The home page** with all its markup and then use BS5 classes for styling the home page.
I also use some custom CSS to overwrite Some of the BS5 classes.
I also used JavaScript to dynamically generate the featured Instructors Section of the home page

2) **The about page:** with all its markup and used BS5 classes for styling and some custom CSS to overwrite some of the BS5 classes

3)**The close button** with its markup and styling and Added javaScript.

4) **Video description** link [Video](https://www.loom.com/share/777ee4f15993418ea31e0fac91c2907c)

2022-09-14 15:19 UTC, Munsa1 requested changes
Hi @ndorrh, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 15:19 UTC, Munsa1 commented on about.html
> +      <!--Footer-->
- [ ] Above the footer there is supposed to be a partner section for both the mobile and desktop view, kindly add it as it is part of the design.

Your design
![image](https://user-images.githubusercontent.com/81932478/190192788-d0a5b4f7-c0de-4f17-86db-cae1e06cf7c2.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/190192956-4914c2c1-6288-4387-b5ae-be5462b59b82.png)

- [ ] Also fix the color of the footer , it is white and not the color which is currently be used.

2022-09-14 19:35 UTC, ichala requested changes
Hi @ndorrh , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No linters errors✅ 
- Added partner section ✅ 


 ## Required Changes ♻️

- [ ] _**check the comments below**_


## Optional suggestions

- [x] N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 19:35 UTC, ichala commented on about.html
>            <span class="line"></span>
- [ ] great job removing the old image, but this title should be an HTML code styled with CSS and not an image, kindly try to remove the image and replace it with HTML Heading and try to style it like the template

![image](https://user-images.githubusercontent.com/89282221/190245676-adb378d4-4150-4159-9042-9a7c4daad604.png)

2022-09-14 21:25 UTC, OLIPLICHE approved these changes
Hi @ndorrh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

##Highlights
- The required Changes were implemented (✅)) 👏
- The web is working fine👏👏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 21:25 UTC, OLIPLICHE commented on index.html
> +          <h3 class="date">Starting on the (THU)15.10.2022 ~ 16(FRI)</h3>
## Optional:
- Please you need to increase the font size. Your page will be more attractive if you follow the design(size) provided by Cindy Shin(The author of the original design). I would like to emphasize that this project can land you in a new career as Frontend Dev. Kindly take this Optional Serious
- 
![Capture](https://user-images.githubusercontent.com/63972670/190264220-eca18db7-9ce4-4dd9-8563-a67819e183b9.PNG)

- Your Design:
![Capture](https://user-images.githubusercontent.com/63972670/190264016-70ff38fc-3b2f-44ab-a8bb-9b33a623040e.PNG)

2022-09-15 06:05 UTC, merged

2022-11-27 05:55 UTC, ndorrh commented on index.html
> +          />
Thanks for the review